import emailjs from 'emailjs-com'
import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SeniorStaff from '../components/SeniorStaff'

export default function Home() {
  return (
    <div >
      <Head>
        <title>SRI-Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SeniorStaff/>
      
    </div>
  )
}
